import { PROMPT_EDITOR_MIN_HEIGHT } from "../config/appConfig";

export const mono = "'JetBrains Mono', monospace";
const sans = "'DM Sans', 'Noto Sans SC', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif";
const THEME_PRIMARY = "#3b82f6";
const THEME_PRIMARY_TEXT = "#bfdbfe";
const THEME_PRIMARY_SOFT = "rgba(59,130,246,0.16)";
const THEME_PRIMARY_BORDER = "rgba(59,130,246,0.45)";
const THEME_EMERALD_TEXT = "#dcfce7";
const THEME_EMERALD_SOFT = "rgba(34,197,94,0.18)";
const THEME_EMERALD_BORDER = "rgba(34,197,94,0.56)";
const THEME_GOLD = "#facc15";
const THEME_GOLD_TEXT = "#fef08a";
const THEME_GOLD_SOFT = "rgba(250,204,21,0.14)";
const THEME_GOLD_BORDER = "rgba(250,204,21,0.55)";
export const S = {
  root: { minHeight: "100vh", background: "#0a0a0b", color: "#e4e4e7", fontFamily: sans, position: "relative" },
  bgGrain: { position: "fixed", inset: 0, background: "radial-gradient(ellipse at 20% 0%, rgba(16,163,127,0.06) 0%, transparent 60%), radial-gradient(ellipse at 80% 100%, rgba(26,115,232,0.04) 0%, transparent 60%)", pointerEvents: "none", zIndex: 0 },
  header: { position: "relative", zIndex: 1, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 28px", borderBottom: "1px solid rgba(255,255,255,0.06)" },
  logoArea: { display: "flex", alignItems: "center", gap: 14 },
  logoCube: { width: 40, height: 40, borderRadius: 10, background: "linear-gradient(135deg, #1a73e8, #10a37f)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700 },
  title: { margin: 0, fontSize: 18, fontFamily: mono, fontWeight: 700, letterSpacing: 3, color: "#fff" },
  subtitle: { margin: 0, fontSize: 11, color: "#888", letterSpacing: 1, textTransform: "uppercase" },
  headerActions: { display: "flex", alignItems: "center", gap: 12 },
  modeNav: { display: "flex", alignItems: "center", gap: 4, padding: 4, borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.04)" },
  modeTab: { padding: "8px 12px", borderRadius: 8, border: "none", background: "transparent", color: "#a1a1aa", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  modeTabActive: { background: THEME_GOLD_SOFT, color: THEME_GOLD },
  apiSwitchWrap: { position: "relative" },
  apiSwitchBtn: { height: 36, padding: "0 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.1)", background: "transparent", color: "#a1a1aa", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  apiSwitchBtnActive: { borderColor: THEME_PRIMARY_BORDER, color: THEME_PRIMARY_TEXT, background: THEME_PRIMARY_SOFT },
  settingsBtn: { width: 36, height: 36, borderRadius: 8, border: "1px solid rgba(255,255,255,0.1)", background: "transparent", color: "#aaa", fontSize: 16, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  main: { position: "relative", zIndex: 1, maxWidth: 1200, margin: "0 auto", padding: "24px 20px 60px" },
  inputGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 136px", gap: 16 },
  inputGridStyle: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 320px", gap: 16 },
  refColumn: { display: "flex", flexDirection: "column" },
  label: { display: "block", fontSize: 11, fontFamily: mono, fontWeight: 600, letterSpacing: 1.5, color: "#999", marginBottom: 8, textTransform: "uppercase" },
  promptHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 8, flexWrap: "wrap" },
  promptHeadActions: { display: "flex", alignItems: "center", gap: 8 },
  inputHint: { fontSize: 12, color: "#71717a", fontFamily: mono },
  placeholderBtn: { height: 20, minWidth: 26, borderRadius: 5, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 10, lineHeight: "18px", cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "0 5px" },
  gptAssistBtn: { width: 20, height: 20, borderRadius: 5, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 11, lineHeight: "18px", cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  comparePromptGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12 },
  textarea: { width: "100%", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: "14px 16px", color: "#e4e4e7", fontFamily: sans, fontSize: 14, resize: "vertical", outline: "none", lineHeight: 1.6 },
  tokenEditor: { width: "100%", boxSizing: "border-box", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: "14px 16px", color: "#e4e4e7", fontFamily: sans, fontSize: 14, outline: "none", lineHeight: 1.6, whiteSpace: "pre-wrap", wordBreak: "break-word", userSelect: "text", WebkitUserSelect: "text", cursor: "text", caretColor: "#f8fafc" },
  dropZone: { width: "100%", height: PROMPT_EDITOR_MIN_HEIGHT, borderRadius: 10, border: "1px dashed rgba(255,255,255,0.12)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", background: "rgba(255,255,255,0.02)" },
  uploadedBox: { position: "relative", width: "100%", height: PROMPT_EDITOR_MIN_HEIGHT, borderRadius: 10, overflow: "hidden", border: "1px solid rgba(255,255,255,0.1)", cursor: "pointer", background: "rgba(255,255,255,0.02)" },
  uploadedThumb: { width: "100%", height: "100%", objectFit: "cover" },
  removeBtn: { position: "absolute", bottom: 6, right: 6, width: 22, height: 22, borderRadius: 11, background: "rgba(0,0,0,0.7)", border: "none", color: "#fff", fontSize: 11, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 3 },
  uploadPairRow: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8, alignItems: "stretch" },
  uploadPairCol: { display: "flex", flexDirection: "column", gap: 6, minWidth: 0 },
  uploadPairTopLabel: { fontSize: 11, color: "#71717a", fontFamily: mono, letterSpacing: 0.5, textTransform: "uppercase" },
  uploadPairBox: { position: "relative", width: "100%", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, background: "rgba(255,255,255,0.03)", padding: 6, cursor: "pointer", textAlign: "left" },
  uploadPairBody: { borderRadius: 8, overflow: "hidden", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.02)", minHeight: 106 },
  uploadPairMainThumb: { width: "100%", height: 106, objectFit: "cover", display: "block" },
  inputImagesGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 6, minHeight: 106 },
  inputImagesCell: { borderRadius: 8, overflow: "hidden", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.02)", minHeight: 50 },
  inputImagesThumb: { width: "100%", height: 50, objectFit: "cover", display: "block" },
  inputImagesEmpty: { minHeight: 50, borderRadius: 8, border: "1px dashed rgba(255,255,255,0.2)", color: "#71717a", fontSize: 18, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(255,255,255,0.02)", width: "100%" },
  inputCountBadge: { position: "absolute", top: 8, right: 8, zIndex: 3, minWidth: 22, height: 22, padding: "0 6px", borderRadius: 11, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(8,47,73,0.88)", color: "#dbeafe", fontFamily: mono, fontSize: 11, display: "inline-flex", alignItems: "center", justifyContent: "center" },
  inputEditBtn: { position: "absolute", top: 8, left: 8, zIndex: 3, height: 22, padding: "0 8px", borderRadius: 11, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(15,23,42,0.82)", color: "#e2e8f0", fontFamily: mono, fontSize: 11, cursor: "pointer" },
  inputDrawBtn: { position: "absolute", left: 8, bottom: 8, zIndex: 3, width: 26, height: 26, borderRadius: 13, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(8,47,73,0.88)", color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 13, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  modelsPanel: { border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: 10, background: "rgba(255,255,255,0.02)", display: "flex", flexDirection: "column", gap: 10, height: "100%" },
  modelsPanelStyle: { width: "100%", maxWidth: "100%" },
  modelsHeadRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 },
  syncBtn: { padding: "6px 10px", borderRadius: 7, border: `1px solid ${THEME_GOLD_BORDER}`, background: THEME_GOLD_SOFT, color: THEME_GOLD_TEXT, fontFamily: mono, fontSize: 11, cursor: "pointer" },
  modelTemplateGrid: { display: "grid", gridTemplateColumns: "minmax(0, 5fr) minmax(0, 3fr)", gap: 12, alignItems: "stretch" },
  modelTemplateGridStyle: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12, alignItems: "stretch" },
  modelGrid: { display: "grid", gap: 8 },
  modelGridStyle: { display: "grid", gap: 8 },
  modelGridRow: { display: "grid", gap: 8 },
  imageSizePanel: { border: "1px solid rgba(255,255,255,0.07)", borderRadius: 8, padding: "8px 10px", background: "rgba(255,255,255,0.015)", marginTop: "auto" },
  imageSizeGroup: { display: "grid", gap: 6, marginBottom: 8 },
  imageSizeGroupTitle: { fontSize: 11, color: "#8b8b93", fontFamily: mono },
  imageSizeBtnRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  imageSizeBtn: { padding: "5px 8px", borderRadius: 7, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(255,255,255,0.03)", color: "#c4c4cc", fontFamily: mono, fontSize: 11, cursor: "pointer" },
  imageSizeBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  imageSizeWarn: { margin: "2px 0 0", fontSize: 11, color: "#a1a1aa", fontFamily: mono, lineHeight: 1.5 },
  templatePanel: { border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: 10, background: "rgba(255,255,255,0.02)", height: "100%" },
  templatePanelHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 6 },
  templateFieldHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  templateStatus: { fontSize: 11, color: "#71717a", fontFamily: mono, marginBottom: 8 },
  templateList: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  styleTemplateList: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  styleThemesPanel: { marginTop: 10, border: "1px solid rgba(255,255,255,0.08)", borderRadius: 8, padding: 8, background: "rgba(255,255,255,0.02)" },
  styleThemesHeadRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 8 },
  styleThemeAssistRow: { display: "grid", gridTemplateColumns: "1fr auto", gap: 8, marginBottom: 8 },
  styleThemeAssistInput: { width: "100%", height: 30, borderRadius: 7, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(0,0,0,0.25)", color: "#e2e8f0", fontFamily: mono, fontSize: 12, padding: "0 8px", outline: "none" },
  styleThemesGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 8 },
  styleThemeInput: { width: "100%", height: 30, borderRadius: 7, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(0,0,0,0.25)", color: "#e2e8f0", fontFamily: mono, fontSize: 12, padding: "0 8px", outline: "none" },
  templateItem: { width: "100%", border: "1px solid rgba(63,63,70,0.9)", borderRadius: 8, padding: "8px 8px 8px 10px", background: "rgba(12,12,14,0.9)", minHeight: 38, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, textAlign: "left", color: "#71717a", cursor: "pointer", userSelect: "none", WebkitTapHighlightColor: "transparent", boxShadow: "none" },
  templateItemDisabled: { opacity: 0.55, cursor: "not-allowed" },
  templateItemActive: { borderColor: THEME_PRIMARY_BORDER, boxShadow: "none", background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  templateItemTitle: { fontSize: 11, color: "inherit", fontFamily: mono, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", flex: 1 },
  templateActions: { display: "inline-flex", alignItems: "center", justifyContent: "center" },
  templateEditBtn: { width: 24, height: 24, borderRadius: 6, border: "1px solid rgba(82,82,91,0.9)", background: "rgba(24,24,27,0.9)", color: "#a1a1aa", fontSize: 12, fontFamily: mono, cursor: "pointer", padding: 0, lineHeight: "24px", textAlign: "center", outline: "none" },
  modelChipWrap: { border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, padding: 5, background: "rgba(255,255,255,0.02)" },
  modelRow: { display: "grid", gridTemplateColumns: "1fr auto", gap: 8, alignItems: "center" },
  modelChip: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 7px", borderRadius: 7, border: "1px solid", color: "#e4e4e7", fontSize: 12, fontFamily: sans, transition: "all 0.15s", width: "100%", minHeight: 32 },
  dot: { width: 6, height: 6, borderRadius: 3, flexShrink: 0 },
  chipName: { fontWeight: 500, fontSize: 11, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 72 },
  chipNameStyleMode: { fontWeight: 500, fontSize: 11, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 72 },
  check: { marginLeft: "auto", color: "#10a37f", fontWeight: 700, fontSize: 14 },
  countRow: { display: "flex", alignItems: "center", gap: 4 },
  countLabel: { fontSize: 11, color: "#999", fontFamily: mono, width: 10, textAlign: "center" },
  countSelect: { width: 50, height: 32, padding: "4px 5px", borderRadius: 6, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(255,255,255,0.04)", color: "#e4e4e7", fontFamily: mono, fontSize: 11, outline: "none" },
  genRow: { display: "flex", gap: 12, marginBottom: 32, alignItems: "center" },
  folderRow: { display: "flex", gap: 10, marginBottom: 10, alignItems: "center", flexWrap: "wrap" },
  atlasRow: { display: "flex", gap: 8, marginBottom: 10, alignItems: "center", flexWrap: "wrap" },
  atlasCount: { fontSize: 12, color: THEME_PRIMARY_TEXT, fontFamily: mono, minWidth: 120 },
  atlasThumbBtn: { width: 54, height: 54, borderRadius: 8, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(8,47,73,0.65)", overflow: "hidden", padding: 0, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center" },
  atlasThumbImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  helpWrap: { display: "grid", gap: 16 },
  helpHero: { borderRadius: 16, border: "1px solid rgba(255,255,255,0.08)", background: "linear-gradient(135deg, rgba(26,115,232,0.2), rgba(16,163,127,0.08))", padding: "22px 24px" },
  helpTitle: { margin: 0, fontSize: 28, fontFamily: mono, color: "#f8fafc", letterSpacing: -0.5 },
  helpTextBlock: { display: "grid", gap: 8 },
  helpIntro: { margin: "10px 0 0", fontSize: 14, color: "#9ca3af", lineHeight: 1.7, maxWidth: 760 },
  helpIntroCn: { margin: 0, fontSize: 14, color: "#a7b0bf", lineHeight: 1.8, maxWidth: 760 },
  helpGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 14 },
  helpCard: { borderRadius: 14, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: "18px 18px 16px" },
  helpCardFull: { gridColumn: "1 / -1" },
  helpCardTitle: { margin: "0 0 8px", fontSize: 13, color: "#f8fafc", fontFamily: mono, textTransform: "uppercase", letterSpacing: 0.6 },
  helpCardText: { margin: 0, fontSize: 13, color: "#98a2b3", lineHeight: 1.7 },
  helpCardTextCn: { margin: 0, fontSize: 13, color: "#a8b1c0", lineHeight: 1.8 },
  helpParagraphGroup: { display: "grid", gap: 8 },
  helpParagraphItem: { display: "grid" },
  helpLangGap: { height: 8 },
  helpInlineCode: { fontFamily: mono, fontSize: "0.95em", color: "#f8fafc", background: "rgba(148,163,184,0.12)", border: "1px solid rgba(148,163,184,0.18)", borderRadius: 6, padding: "1px 6px", margin: "0 2px" },
  folderHint: { fontSize: 12, color: "#a1a1aa", fontFamily: mono },
  folderMsg: { fontSize: 12, color: THEME_PRIMARY_TEXT, marginBottom: 18, fontFamily: mono },
  genBtn: { padding: "12px 32px", borderRadius: 10, border: "none", background: "linear-gradient(135deg, #1a73e8, #10a37f)", color: "#fff", fontFamily: mono, fontSize: 14, fontWeight: 600, cursor: "pointer" },
  zipBtn: { padding: "12px 24px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)", color: "#e4e4e7", fontFamily: mono, fontSize: 13, cursor: "pointer" },
  btnSpin: { display: "inline-block", width: 14, height: 14, border: "2px solid rgba(255,255,255,0.3)", borderTopColor: "#fff", borderRadius: "50%", animation: "spin 0.6s linear infinite" },
  resultCol: { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 12, padding: 16, minHeight: 200 },
  resultHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14, paddingBottom: 10, borderBottom: "1px solid rgba(255,255,255,0.06)" },
  resultName: { fontFamily: mono, fontSize: 13, fontWeight: 600, flex: 1 },
  statusBadge: { fontSize: 11, fontWeight: 600, padding: "3px 8px", borderRadius: 6, textTransform: "capitalize" },
  loadingArea: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "40px 0" },
  spinner: { width: 32, height: 32, border: "3px solid rgba(59,130,246,0.2)", borderTopColor: THEME_PRIMARY, borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  errArea: { padding: "20px 12px" },
  imgGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 10 },
  imgGridCompact: { display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 6 },
  imgCard: { position: "relative", borderRadius: 8, overflow: "hidden", background: "#111", border: "1px solid transparent", boxShadow: "none" },
  imgCardCompact: { borderRadius: 6 },
  imgCardSelected: { borderColor: "rgba(59,130,246,0.9)", boxShadow: "0 0 0 1px rgba(59,130,246,0.35) inset" },
  imageSelectBtn: { position: "absolute", top: 8, right: 8, zIndex: 3, width: 24, height: 24, borderRadius: 12, border: "1px solid rgba(226,232,240,0.7)", background: "rgba(15,23,42,0.72)", color: "rgba(226,232,240,0.88)", fontFamily: mono, fontSize: 12, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0, lineHeight: 1, outline: "none", boxShadow: "none", WebkitAppearance: "none", appearance: "none", WebkitTapHighlightColor: "transparent" },
  imageSelectBtnCompact: { top: 4, right: 4, width: 16, height: 16, borderRadius: 8, fontSize: 10 },
  imageSelectBtnBottom: { top: "auto", bottom: 4, right: 4 },
  imageSelectBtnActive: { borderColor: "rgba(16,163,127,0.9)", background: "rgba(5,150,105,0.92)", color: "#dcfce7" },
  imageSplitBtn: { position: "absolute", bottom: 38, right: 8, zIndex: 3, width: 26, height: 26, borderRadius: 13, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(8,47,73,0.82)", color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 12, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0, lineHeight: 1, outline: "none", boxShadow: "none", WebkitAppearance: "none", appearance: "none", WebkitTapHighlightColor: "transparent" },
  imageSplitBtnCompact: { width: 18, height: 18, borderRadius: 9, right: 4, bottom: 32, fontSize: 10 },
  imageSplitBtnBusy: { opacity: 0.65, cursor: "wait" },
  imageThemeTag: { position: "absolute", left: 8, top: 8, zIndex: 2, maxWidth: "70%", padding: "2px 7px", borderRadius: 999, fontSize: 10, fontFamily: mono, color: THEME_PRIMARY_TEXT, background: "rgba(6,78,59,0.82)", border: `1px solid ${THEME_PRIMARY_BORDER}`, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  imageThemeTagCompact: { left: 4, top: 4, maxWidth: "75%", padding: "1px 5px", fontSize: 9, borderRadius: 999 },
  thumb: { width: "100%", height: "auto", objectFit: "contain", cursor: "pointer", display: "block", background: "#0b0b0d" },
  thumbCompact: { width: "100%", height: "auto", objectFit: "contain", cursor: "pointer", display: "block", background: "#0b0b0d", maxHeight: 220 },
  thumbRetrying: { width: "100%", minHeight: 180, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(2,6,23,0.65)", color: "#cbd5e1", fontFamily: mono, fontSize: 12 },
  thumbRetryingCompact: { width: "100%", minHeight: 120, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(2,6,23,0.65)", color: "#cbd5e1", fontFamily: mono, fontSize: 10 },
  imageActionBar: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(255,255,255,0.03)" },
  imageActionBarCompact: { minHeight: 28 },
  imageActionBtn: { height: 34, border: "none", borderRight: "1px solid rgba(255,255,255,0.06)", background: "transparent", color: "#cbd5e1", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  imageActionBtnCompact: { height: 28, border: "none", borderRight: "1px solid rgba(255,255,255,0.06)", background: "transparent", color: "#cbd5e1", fontFamily: mono, fontSize: 11, cursor: "pointer" },
  imageActionBtnBusy: { opacity: 0.6, cursor: "wait" },
  imageActionBtnDisabled: { opacity: 0.35, cursor: "not-allowed" },
  imageActionIcon: { fontSize: 18, lineHeight: 1, fontWeight: 700 },
  imageActionIconCompact: { fontSize: 16, lineHeight: 1, fontWeight: 700 },
  imageActionPlus: { fontSize: 13, lineHeight: 1, fontWeight: 700 },
  imageActionPlusCompact: { fontSize: 12, lineHeight: 1, fontWeight: 700 },
  dlBtn: { width: "100%", padding: "8px 0", border: "none", borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(255,255,255,0.04)", color: "#aaa", fontSize: 12, fontFamily: mono, cursor: "pointer" },
  modalOverlay: { position: "fixed", inset: 0, zIndex: 1000, background: "rgba(0,0,0,0.8)", backdropFilter: "blur(8px)", display: "flex", alignItems: "center", justifyContent: "center", animation: "fadeIn 0.15s ease" },
  previewNavBtn: { position: "absolute", top: "50%", transform: "translateY(-50%)", zIndex: 11, width: 38, height: 38, borderRadius: 19, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(2,6,23,0.74)", color: "#f8fafc", fontSize: 24, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  previewCounter: { position: "absolute", top: 14, left: "50%", transform: "translateX(-50%)", zIndex: 11, minWidth: 72, height: 28, padding: "0 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(2,6,23,0.74)", color: "#e2e8f0", fontFamily: mono, fontSize: 12, display: "inline-flex", alignItems: "center", justifyContent: "center" },
  previewCompareGrid: { width: "100%", height: "100%", display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: 0 },
  previewComparePane: { minWidth: 0, minHeight: 0, display: "grid", gridTemplateRows: "auto minmax(0, 1fr)", borderRight: "1px solid rgba(255,255,255,0.08)" },
  previewCompareLabel: { minHeight: 42, display: "flex", alignItems: "center", gap: 8, padding: "8px 14px", borderBottom: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", color: "#cbd5e1", fontFamily: mono, fontSize: 12, letterSpacing: 0.5, textTransform: "uppercase", flexWrap: "wrap" },
  previewCompareTokens: { display: "inline-flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  previewCompareToken: { padding: "2px 8px", borderRadius: 999, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontSize: 11, letterSpacing: 0, textTransform: "none" },
  previewCompareImageWrap: { minWidth: 0, minHeight: 0, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", background: "#0b0b0d" },
  previewCompareImage: { maxWidth: "100%", maxHeight: "100%", objectFit: "contain" },
  previewSingleWrap: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", background: "#0b0b0d" },
  viewerMetaBar: { position: "absolute", top: 14, left: 14, zIndex: 12, display: "inline-flex", alignItems: "center", gap: 8, maxWidth: "min(calc(100% - 116px), 52vw)", flexWrap: "nowrap" },
  viewerMetaBarInline: { position: "static", top: "auto", left: "auto", zIndex: "auto", maxWidth: "100%", minWidth: 0 },
  viewerMetaChip: { minWidth: 0, maxWidth: "100%", height: 28, padding: "0 10px", borderRadius: 999, border: `1px solid ${THEME_EMERALD_BORDER}`, background: THEME_EMERALD_SOFT, color: THEME_EMERALD_TEXT, fontFamily: mono, fontSize: 12, display: "inline-flex", alignItems: "center", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  viewerPromptBtn: { width: 28, height: 28, borderRadius: 14, border: `1px solid ${THEME_EMERALD_BORDER}`, background: THEME_EMERALD_SOFT, color: THEME_EMERALD_TEXT, fontFamily: mono, fontSize: 12, fontWeight: 600, display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0, userSelect: "none", padding: 0 },
  viewerPromptPanel: { position: "absolute", top: 52, right: 16, zIndex: 14, width: "min(520px, calc(100% - 32px))", maxHeight: "min(58vh, 520px)", overflow: "auto", borderRadius: 10, border: "1px solid rgba(255,255,255,0.18)", background: "rgba(24,24,27,0.94)", color: "#f8fafc", fontFamily: mono, fontSize: 12, lineHeight: 1.55, whiteSpace: "pre-wrap", wordBreak: "break-word", padding: "12px 14px", boxShadow: "0 18px 50px rgba(0,0,0,0.36)" },
  viewerToast: { position: "absolute", left: "50%", bottom: 22, transform: "translateX(-50%)", zIndex: 20, minHeight: 32, padding: "0 14px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(2,6,23,0.86)", color: "#f8fafc", fontFamily: mono, fontSize: 12, display: "inline-flex", alignItems: "center", justifyContent: "center", boxShadow: "0 10px 28px rgba(0,0,0,0.32)" },
  viewerColorPickerBar: { position: "absolute", top: 14, right: 56, zIndex: 12, display: "inline-flex", alignItems: "center", gap: 8, maxWidth: "min(52vw, calc(100% - 112px))" },
  viewerColorPickerBtn: { width: 28, height: 28, borderRadius: 14, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(2,6,23,0.74)", color: "#e2e8f0", fontFamily: mono, fontSize: 14, lineHeight: 1, cursor: "crosshair", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0, flexShrink: 0 },
  viewerColorPickerBtnActive: { borderColor: THEME_GOLD_BORDER, background: THEME_GOLD_SOFT, color: THEME_GOLD_TEXT },
  viewerColorValue: { minWidth: 0, maxWidth: "100%", height: 28, padding: "0 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(2,6,23,0.74)", color: "#e2e8f0", fontFamily: mono, fontSize: 12, display: "inline-flex", alignItems: "center", gap: 8, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  viewerColorSwatch: { width: 14, height: 14, borderRadius: 7, border: "1px solid rgba(255,255,255,0.42)", flexShrink: 0 },
  viewerColorHistoryPanel: { position: "absolute", top: 52, right: 16, zIndex: 13, width: 190, maxHeight: "min(42vh, 380px)", overflow: "hidden", borderRadius: 10, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(2,6,23,0.78)", color: "#e2e8f0", boxShadow: "0 14px 38px rgba(0,0,0,0.32)", display: "grid", gridTemplateRows: "auto minmax(0, 1fr)" },
  viewerColorHistoryTitle: { height: 30, padding: "0 10px", display: "flex", alignItems: "center", borderBottom: "1px solid rgba(255,255,255,0.08)", color: "#a1a1aa", fontFamily: mono, fontSize: 11, textTransform: "uppercase", letterSpacing: 0.4 },
  viewerColorHistoryList: { overflow: "auto", display: "grid", gap: 4, padding: 6 },
  viewerColorHistoryItem: { width: "100%", minWidth: 0, height: 30, padding: "0 8px", borderRadius: 8, border: "1px solid transparent", background: "transparent", color: "#e2e8f0", fontFamily: mono, fontSize: 11, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, textAlign: "left" },
  viewerColorHistoryItemActive: { borderColor: "rgba(248,113,113,0.72)", background: "rgba(127,29,29,0.3)", color: "#fee2e2" },
  viewerColorHistoryText: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  viewerColorMarker: { position: "absolute", zIndex: 16, width: 22, height: 22, borderRadius: 11, border: "2px solid #ef4444", background: "rgba(239,68,68,0.12)", transform: "translate(-50%, -50%)", boxShadow: "0 0 0 2px rgba(255,255,255,0.7), 0 0 18px rgba(239,68,68,0.6)", pointerEvents: "none" },
  settingsModal: { width: "90%", maxWidth: 560, background: "#161618", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 16, padding: 28, maxHeight: "80vh", overflow: "auto" },
  closeBtn: { width: 32, height: 32, borderRadius: 8, border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.05)", color: "#aaa", fontSize: 14, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  fieldLabel: { display: "block", fontSize: 12, fontFamily: mono, fontWeight: 500, color: "#999", marginBottom: 6 },
  proxyInput: { width: "100%", padding: "10px 14px", borderRadius: 8, border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.04)", color: "#e4e4e7", fontFamily: mono, fontSize: 14, outline: "none" },
  hint: { fontSize: 12, color: "#888", marginTop: 8, lineHeight: 1.5 },
  settingToggleList: { marginTop: 2, display: "grid", gap: 10 },
  settingToggleRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "10px 12px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)" },
  settingToggleTextWrap: { minWidth: 0, display: "grid", gap: 3 },
  settingToggleTitle: { fontSize: 13, color: "#e4e4e7", fontFamily: mono },
  settingToggleHint: { fontSize: 12, color: "#888", lineHeight: 1.5 },
  settingToggleBtn: { minWidth: 62, height: 30, padding: "0 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(255,255,255,0.03)", color: "#a1a1aa", fontFamily: mono, fontSize: 12, cursor: "pointer", flexShrink: 0 },
  settingToggleBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  toggleCodeBtn: { padding: "8px 16px", borderRadius: 6, border: "1px solid rgba(255,255,255,0.1)", background: "transparent", color: "#aaa", fontSize: 12, fontFamily: mono, cursor: "pointer" },
  codeBlock: { marginTop: 12, padding: 16, background: "#0d0d0f", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, fontSize: 11, fontFamily: mono, color: "#a0a0b0", overflow: "auto", maxHeight: 300, lineHeight: 1.6, whiteSpace: "pre-wrap", wordBreak: "break-word" },
  apiModalActions: { marginTop: 12, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 },
  apiModalState: { fontSize: 12, color: "#a1a1aa", fontFamily: mono },
  apiSaveBtn: { padding: "8px 14px", borderRadius: 8, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 12, cursor: "pointer" },
  inputImagesModal: { maxWidth: 820 },
  modalInputImagesHint: { marginBottom: 12, fontSize: 12, color: "#a1a1aa", fontFamily: mono, lineHeight: 1.5 },
  modalInputImagesGrid: { display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", gap: 10 },
  modalInputImageCell: { position: "relative", borderRadius: 10, overflow: "hidden", border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT },
  modalInputImageThumb: { width: "100%", aspectRatio: "1 / 1", objectFit: "cover", display: "block" },
  modalInputImageRemoveBtn: { position: "absolute", top: 8, right: 8, width: 22, height: 22, borderRadius: 11, border: "none", background: "rgba(15,23,42,0.8)", color: "#e2e8f0", cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center" },
  modalInputImageEmpty: { aspectRatio: "1 / 1", borderRadius: 10, border: `1px dashed ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 24, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", padding: 0, gap: 6 },
  modalInputImageEmptyDisabled: { opacity: 0.45, cursor: "not-allowed" },
  modalInputImageUploadPlus: { fontSize: 28, lineHeight: 1 },
  modalInputImageUploadText: { fontSize: 12, letterSpacing: 0.4, textTransform: "uppercase" },
  modalInputImagesActions: { marginTop: 10, display: "flex", justifyContent: "flex-end", gap: 8, flexWrap: "wrap" },
  inputImageEditorModal: { width: "min(1180px, 96vw)", maxHeight: "92vh", overflow: "auto", background: "#161618", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 18, padding: 18, display: "grid", gap: 16 },
  inputImageEditorHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  inputImageEditorHeaderHint: { marginTop: 6, fontSize: 12, color: "#9ca3af", lineHeight: 1.6, maxWidth: 560, fontFamily: mono },
  inputImageEditorLayout: { display: "grid", gridTemplateColumns: "240px minmax(0, 1fr)", gap: 16, minHeight: 0 },
  inputImageEditorSidebar: { minWidth: 0, display: "flex", flexDirection: "column", gap: 12, padding: 12, borderRadius: 14, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)" },
  inputImageEditorMain: { minWidth: 0, display: "grid", gap: 12 },
  inputImageEditorBlock: { display: "grid", gap: 8 },
  inputImageEditorLabel: { fontSize: 11, color: "#a1a1aa", fontFamily: mono, letterSpacing: 1.2, textTransform: "uppercase" },
  inputImageEditorToolGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  inputImageEditorToolBtn: { height: 34, borderRadius: 9, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)", color: "#d4d4d8", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  inputImageEditorToolBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  inputImageEditorColorRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  inputImageEditorColorBtn: { width: 28, height: 28, borderRadius: 14, border: "1px solid rgba(255,255,255,0.14)", cursor: "pointer", boxShadow: "inset 0 0 0 1px rgba(2,6,23,0.2)" },
  inputImageEditorColorBtnActive: { boxShadow: `0 0 0 2px ${THEME_PRIMARY}, inset 0 0 0 1px rgba(2,6,23,0.28)` },
  inputImageEditorNavRow: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  inputImageEditorMiniBtn: { height: 32, borderRadius: 9, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)", color: "#d4d4d8", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  inputImageEditorMiniBtnDisabled: { opacity: 0.45, cursor: "not-allowed" },
  inputImageEditorStatus: { minHeight: 18, fontSize: 12, color: THEME_PRIMARY_TEXT, fontFamily: mono, lineHeight: 1.5 },
  inputImageEditorSubHint: { fontSize: 11, color: "#a1a1aa", fontFamily: mono, lineHeight: 1.5 },
  inputImageEditorActionGrid: { display: "grid", gap: 8 },
  inputImageEditorActionBtn: { height: 36, borderRadius: 9, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontFamily: mono, fontSize: 12, cursor: "pointer" },
  inputImageEditorGhostBtn: { height: 36, borderRadius: 9, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)", color: "#d4d4d8", fontFamily: mono, fontSize: 12, cursor: "pointer" },
  inputImageEditorConfirmBtn: { height: 38, borderRadius: 10, border: "none", background: "linear-gradient(135deg, #1a73e8, #10a37f)", color: "#fff", fontFamily: mono, fontSize: 12, fontWeight: 600, cursor: "pointer" },
  inputImageEditorActionBtnDisabled: { opacity: 0.45, cursor: "not-allowed" },
  inputImageEditorViewport: { position: "relative", minHeight: 520, height: "min(58vh, 560px)", borderRadius: 14, border: "1px solid rgba(255,255,255,0.08)", background: "#09090b", overflow: "hidden" },
  inputImageEditorCanvas: { width: "100%", height: "100%", display: "block", touchAction: "none" },
  inputImageEditorThumbStrip: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(84px, 1fr))", gap: 10 },
  inputImageEditorThumbBtn: { position: "relative", borderRadius: 10, overflow: "hidden", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.03)", padding: 0, cursor: "pointer", minHeight: 84 },
  inputImageEditorThumbBtnActive: { borderColor: THEME_PRIMARY_BORDER, boxShadow: `0 0 0 1px ${THEME_PRIMARY_BORDER} inset` },
  inputImageEditorThumbImg: { width: "100%", height: 84, objectFit: "cover", display: "block", background: "#0b0b0d" },
  inputImageEditorThumbIndex: { position: "absolute", left: 6, bottom: 6, minWidth: 20, height: 20, padding: "0 6px", borderRadius: 10, background: "rgba(2,6,23,0.78)", color: "#f8fafc", fontSize: 11, fontFamily: mono, display: "inline-flex", alignItems: "center", justifyContent: "center" },
  selectionLimitModal: { width: "min(420px, 90vw)", borderRadius: 16, border: "1px solid rgba(255,255,255,0.12)", background: "#161618", padding: "24px 22px", boxShadow: "0 18px 60px rgba(0,0,0,0.35)" },
  selectionLimitTitle: { fontSize: 18, color: "#f8fafc", fontFamily: mono, marginBottom: 8 },
  selectionLimitText: { fontSize: 13, color: "#cbd5e1", lineHeight: 1.6 },
  atlasModalHint: { fontSize: 12, color: "#a1a1aa", fontFamily: mono, marginBottom: 14 },
  atlasModalGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 12 },
  atlasModalCard: { position: "relative", borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", overflow: "hidden", cursor: "grab" },
  atlasModalCardDragging: { opacity: 0.5, transform: "scale(0.98)" },
  atlasModalCardOrder: { position: "absolute", top: 8, left: 8, zIndex: 2, minWidth: 24, height: 24, padding: "0 6px", borderRadius: 12, background: "rgba(2,6,23,0.78)", color: "#f8fafc", fontFamily: mono, fontSize: 11, display: "inline-flex", alignItems: "center", justifyContent: "center" },
  atlasModalCardThumb: { width: "100%", aspectRatio: "1 / 1", objectFit: "cover", display: "block", background: "#0b0b0d" },
  atlasModalCardMeta: { padding: "10px 10px 12px", display: "grid", gap: 4 },
  atlasModalCardTitle: { fontSize: 12, color: "#f4f4f5", fontFamily: mono, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  atlasModalCardSub: { fontSize: 11, color: "#a1a1aa", fontFamily: mono, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  atlasModalPreview: { marginTop: 16, borderRadius: 12, overflow: "hidden", border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)" },
  atlasModalPreviewImg: { width: "100%", display: "block", objectFit: "contain", background: "#0b0b0d" },
  splitModal: { width: "min(1220px, 96vw)", maxHeight: "90vh", overflow: "auto", background: "#161618", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 16, padding: 18, display: "grid", gap: 12 },
  splitPagePanel: { width: "100%", maxHeight: "none", overflow: "visible", boxSizing: "border-box" },
  splitPageSetupGrid: { display: "grid", gridTemplateColumns: "minmax(320px, 0.95fr) minmax(360px, 1.05fr)", gap: 12, alignItems: "stretch" },
  splitPageResultsPanel: { borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: 12, display: "grid", gap: 10, alignContent: "start" },
  splitPageResultsBody: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(0,0,0,0.2)", padding: 12, minHeight: 360, overflow: "visible", alignContent: "start" },
  splitPageResultGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(148px, 1fr))", gap: 12, alignContent: "start" },
  splitPageProcessPanel: { display: "grid", gap: 8, minWidth: 0, alignContent: "start" },
  splitPageProcessStack: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10, alignItems: "start" },
  splitPageProcessWrap: { position: "relative", borderRadius: 10, overflow: "hidden", border: "1px solid rgba(255,255,255,0.08)", background: "#0b0b0d", minHeight: 300, display: "flex", alignItems: "center", justifyContent: "center" },
  splitHistoryPanel: { borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.025)", padding: 12, display: "grid", gap: 10, alignContent: "start" },
  splitHistoryList: { display: "grid", gap: 12 },
  splitHistoryRecord: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(0,0,0,0.2)", padding: 10, display: "grid", gap: 10 },
  splitHistoryRecordHead: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10, flexWrap: "wrap" },
  splitHistoryRecordTitle: { display: "flex", alignItems: "center", gap: 8, color: "#e4e4e7", fontFamily: mono, fontSize: 12, fontWeight: 600 },
  splitHistoryMeta: { color: "#94a3b8", fontFamily: mono, fontSize: 11 },
  splitHistoryModeRow: { display: "flex", alignItems: "center", justifyContent: "flex-start", gap: 8, flexWrap: "wrap" },
  splitHistoryRecordBody: { display: "grid", gap: 12, alignItems: "start" },
  splitHistoryProcessRow: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 8, alignItems: "stretch" },
  splitHistoryProcessCol: { display: "grid", gap: 8 },
  splitHistoryProcessBtn: { width: "100%", border: "1px solid rgba(255,255,255,0.08)", background: "rgba(2,6,23,0.42)", borderRadius: 8, padding: 6, display: "grid", gridTemplateRows: "auto minmax(320px, 1fr)", gap: 5, cursor: "zoom-in", textAlign: "left", minHeight: 350, minWidth: 0 },
  splitHistoryProcessLabel: { color: "#94a3b8", fontFamily: mono, fontSize: 10 },
  splitHistoryProcessImg: { width: "100%", height: 320, objectFit: "contain", display: "block", background: "#0b0b0d", borderRadius: 6 },
  splitHistoryGrid: { display: "grid", gridTemplateColumns: "repeat(10, minmax(0, 1fr))", gap: 10, alignContent: "start" },
  splitHistoryCompareGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 10, alignContent: "start" },
  splitHistoryCompareCard: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8, borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(0,0,0,0.18)", padding: 8 },
  splitHistoryComparePane: { border: "1px solid rgba(255,255,255,0.08)", background: "rgba(2,6,23,0.42)", borderRadius: 8, padding: 6, display: "grid", gap: 5, cursor: "zoom-in", textAlign: "left", minWidth: 0 },
  splitHistoryErrorBox: { borderRadius: 8, border: "1px dashed rgba(248,113,113,0.45)", background: "rgba(127,29,29,0.18)", color: "#fecaca", fontFamily: mono, fontSize: 12, padding: "16px 14px", lineHeight: 1.65, wordBreak: "break-word", textAlign: "center" },
  splitHistoryErrorHint: { marginTop: 6, color: "#fca5a5", fontSize: 11 },
  splitModalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 },
  splitModalTitleRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", minWidth: 0 },
  splitHeaderRight: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  splitTimingText: { color: "#94a3b8", fontFamily: mono, fontSize: 11, whiteSpace: "nowrap" },
  splitMainGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 12, alignItems: "start" },
  splitLeftCol: { display: "grid", gap: 10, alignContent: "start" },
  splitRightCol: { borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: 10, display: "grid", gap: 10, minHeight: 520, alignContent: "start" },
  splitRightTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, flexWrap: "wrap" },
  splitTopActions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  splitRightBody: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(0,0,0,0.2)", padding: 10, minHeight: 430, overflow: "visible", alignContent: "start" },
  splitPane: { borderRadius: 12, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: 10, display: "grid", gap: 8, alignContent: "start", minHeight: 300 },
  splitProcessStack: { display: "grid", gap: 10 },
  splitProcessBlock: { display: "grid", gap: 6, minWidth: 0 },
  splitProcessSubTitle: { color: "#94a3b8", fontFamily: mono, fontSize: 11, letterSpacing: 0.4, textTransform: "uppercase" },
  splitMidActions: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(2,6,23,0.38)", padding: 8, display: "grid", gap: 8, alignContent: "start" },
  splitMidActionRow: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "flex-start" },
  splitToggleGroup: { display: "inline-flex", alignItems: "center", gap: 6, flexWrap: "wrap", padding: 2, borderRadius: 999, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(2,6,23,0.48)", minWidth: 0, maxWidth: "100%" },
  splitToggleBtn: { height: 26, padding: "0 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(255,255,255,0.03)", color: "#cbd5e1", fontFamily: mono, fontSize: 11, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", whiteSpace: "nowrap" },
  splitToggleBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  splitPaneTitle: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, fontSize: 12, color: "#e4e4e7", fontFamily: mono, textTransform: "uppercase", letterSpacing: 0.4 },
  splitPaneCount: { fontSize: 11, color: "#94a3b8", textTransform: "none", letterSpacing: 0, marginLeft: "auto" },
  splitOriginalWrap: { position: "relative", borderRadius: 10, overflow: "hidden", border: "1px solid rgba(255,255,255,0.08)", background: "#0b0b0d", minHeight: 260, display: "flex", alignItems: "center", justifyContent: "center" },
  splitImageWrap: { position: "relative", width: "100%", height: "100%" },
  splitOriginalImg: { width: "100%", maxHeight: 520, objectFit: "contain", display: "block", cursor: "zoom-in" },
  splitImageZoomBtn: { position: "absolute", top: 8, right: 8, zIndex: 3, width: 24, height: 24, borderRadius: 12, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(2,6,23,0.82)", color: "#e2e8f0", fontSize: 12, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  splitImageZoomBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  splitImageUploadBtn: { position: "absolute", right: 8, bottom: 8, zIndex: 4, height: 24, minWidth: 68, padding: "0 8px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.2)", background: "rgba(2,6,23,0.88)", color: "#e2e8f0", fontSize: 11, fontFamily: mono, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center" },
  splitPaneInlineZoomViewer: { width: "100%", maxWidth: "100%", height: "min(520px, 62vh)", borderRadius: 10, border: "1px solid rgba(59,130,246,0.45)", background: "rgba(8,47,73,0.24)", boxShadow: "0 0 0 1px rgba(59,130,246,0.16), 0 10px 24px rgba(2,6,23,0.24)" },
  splitPaneInlineZoomCollapseBtn: { top: 8, right: 8, width: 24, height: 24, borderRadius: 12, fontSize: 12 },
  splitGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10, alignContent: "start" },
  splitItemCell: { position: "relative" },
  splitItemBtn: { position: "relative", width: "100%", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(2,6,23,0.5)", borderRadius: 10, overflow: "hidden", padding: 0, cursor: "zoom-in", textAlign: "left" },
  splitItemBtnWhiteBg: { background: "#ffffff" },
  splitItemOrder: { position: "absolute", top: 6, left: 6, minWidth: 20, height: 20, borderRadius: 10, padding: "0 6px", background: "rgba(2,6,23,0.78)", color: "#f8fafc", fontFamily: mono, fontSize: 10, display: "inline-flex", alignItems: "center", justifyContent: "center", zIndex: 2 },
  splitItemImg: { width: "100%", minHeight: 160, maxHeight: 280, objectFit: "contain", display: "block", background: "#020617" },
  splitItemSelectBtn: { position: "absolute", top: 6, right: 54, zIndex: 3, width: 20, height: 20, borderRadius: 10, border: "1px solid rgba(148,163,184,0.65)", background: "rgba(15,23,42,0.86)", color: "#e2e8f0", fontSize: 11, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  splitItemSelectBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  splitItemZoomBtn: { position: "absolute", top: 6, right: 30, zIndex: 3, width: 20, height: 20, borderRadius: 10, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(2,6,23,0.82)", color: "#e2e8f0", fontSize: 11, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  splitItemZoomBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  splitItemDeleteBtn: { position: "absolute", top: 6, right: 6, zIndex: 3, width: 20, height: 20, borderRadius: 10, border: "1px solid rgba(248,113,113,0.65)", background: "rgba(127,29,29,0.88)", color: "#fee2e2", fontSize: 11, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  splitItemInlineZoomViewer: { width: "100%", maxWidth: "100%", height: 160, borderRadius: 10, border: "1px solid rgba(59,130,246,0.45)", background: "rgba(8,47,73,0.24)", boxShadow: "0 0 0 1px rgba(59,130,246,0.16), 0 10px 24px rgba(2,6,23,0.24)" },
  splitItemInlineZoomCollapseBtn: { width: 22, height: 22, borderRadius: 11, top: 6, right: 6, fontSize: 11 },
  splitStatusText: { minHeight: 18, fontSize: 12, color: "#94a3b8", fontFamily: mono, wordBreak: "break-word" },
  splitStatusTextError: { color: "#fca5a5" },
  turnActionBtn: { height: 28, padding: "0 10px", borderRadius: 6, border: "1px solid rgba(255,255,255,0.2)", background: "rgba(255,255,255,0.04)", color: "#d4d4d8", fontSize: 11, fontFamily: mono, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: 1 },
  turnPromptRow: { marginBottom: 10, display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  turnPromptRowExpanded: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 320px", alignItems: "stretch", justifyContent: "stretch" },
  turnModeBadge: { display: "inline-flex", alignItems: "center", marginLeft: 8, padding: "2px 8px", borderRadius: 999, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT, fontSize: 11, fontFamily: mono },
  turnPromptCards: { flex: "1 1 320px", minWidth: 220, display: "grid", gap: 10 },
  turnPromptCardsExpanded: { height: 320, minHeight: 320, alignSelf: "stretch", gridAutoRows: "1fr" },
  turnPromptCard: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.06)", background: "rgba(255,255,255,0.03)", padding: "12px 14px" },
  turnPromptCardCompact: { maxHeight: 96, overflow: "hidden" },
  turnPromptCardExpanded: { height: "100%", maxHeight: 320, minHeight: 320, overflow: "hidden", display: "flex", flexDirection: "column" },
  turnPromptBadge: { display: "inline-flex", alignItems: "center", padding: "2px 8px", borderRadius: 999, background: THEME_GOLD_SOFT, color: THEME_GOLD, fontSize: 10, fontFamily: mono, marginBottom: 8 },
  turnPromptText: { fontSize: 13, color: "#e4e4e7", whiteSpace: "pre-wrap", lineHeight: 1.5 },
  turnPromptTextCompact: { maxHeight: 72, overflow: "hidden" },
  turnPromptTextExpanded: { flex: 1, maxHeight: "100%", overflow: "hidden" },
  promptChipReadonly: { background: "rgba(59,130,246,0.18)", color: THEME_PRIMARY_TEXT, border: "1px solid rgba(59,130,246,0.62)", borderRadius: 6, padding: "1px 6px", display: "inline-block", margin: "0 1px" },
  styleHistorySummary: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: 10, display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 8 },
  styleSummaryItem: { borderRadius: 8, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(0,0,0,0.24)", padding: "8px 10px", display: "grid", gap: 4 },
  styleSummaryKey: { fontSize: 10, color: "#71717a", fontFamily: mono, textTransform: "uppercase", letterSpacing: 0.4 },
  styleSummaryVal: { fontSize: 12, color: "#e4e4e7", fontFamily: mono, fontWeight: 600 },
  turnStyleUnifiedWrap: { display: "grid", gap: 10 },
  turnStyleFailedLine: { borderRadius: 8, border: "1px solid rgba(239,68,68,0.35)", background: "rgba(127,29,29,0.2)", color: "#fca5a5", fontFamily: mono, fontSize: 11, padding: "7px 10px" },
  turnStyleImageBox: { borderRadius: 10, border: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.03)", padding: 10, display: "grid", gap: 8 },
  turnStyleImageHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, flexWrap: "wrap" },
  turnStyleImageEmpty: { borderRadius: 8, border: "1px dashed rgba(255,255,255,0.14)", background: "rgba(0,0,0,0.2)", color: "#71717a", fontFamily: mono, fontSize: 12, padding: "14px 10px", textAlign: "center" },
  turnCompareResultsGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12 },
  turnStyleResultsGrid: { display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 10 },
  turnResultGroup: { marginTop: 16 },
  turnResultGroupHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 10, flexWrap: "wrap" },
  turnResultMeta: { fontSize: 11, color: "#71717a", fontFamily: mono },
  turnRefViewerCol: { display: "grid", gap: 10, alignItems: "start", justifyItems: "start", flex: "0 0 auto", minWidth: 0 },
  turnRefViewerColExpanded: { width: 320, minWidth: 320, height: 320, alignSelf: "stretch" },
  turnRefImageStack: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", overflowX: "auto", paddingBottom: 2, maxWidth: "100%" },
  turnRefImageWrap: { position: "relative", flexShrink: 0 },
  turnRefImageBtn: { width: 96, height: 96, borderRadius: 8, padding: 0, border: "1px solid rgba(255,255,255,0.1)", overflow: "hidden", background: "transparent", cursor: "zoom-in", flexShrink: 0 },
  turnRefImageZoomBtn: { position: "absolute", top: 6, right: 6, zIndex: 3, width: 24, height: 24, borderRadius: 12, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(2,6,23,0.82)", color: "#e2e8f0", fontSize: 12, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  turnRefImageZoomBtnActive: { borderColor: THEME_PRIMARY_BORDER, background: THEME_PRIMARY_SOFT, color: THEME_PRIMARY_TEXT },
  turnRefImage: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  inlineZoomViewer: { position: "relative", width: 320, maxWidth: "min(320px, 100%)", height: 320, borderRadius: 12, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(8,47,73,0.22)", boxShadow: "0 0 0 1px rgba(59,130,246,0.18), 0 12px 30px rgba(2,6,23,0.28)", overflow: "hidden", flexShrink: 0 },
  inlineZoomViewerCollapseBtn: { position: "absolute", top: 8, right: 8, zIndex: 4, width: 26, height: 26, borderRadius: 13, border: `1px solid ${THEME_PRIMARY_BORDER}`, background: "rgba(2,6,23,0.78)", color: THEME_PRIMARY_TEXT, fontSize: 13, lineHeight: 1, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0 },
  inlineZoomViewerViewport: { width: "100%", height: "100%", overflow: "hidden", background: "#0b0b0d", display: "flex", alignItems: "center", justifyContent: "center", userSelect: "none" },
  inlineZoomViewerImage: { maxWidth: "100%", maxHeight: "100%", objectFit: "contain", transformOrigin: "center center", willChange: "transform", userSelect: "none" },
};
